# Set true color
# set-option -sa terminal-overrides ",xterm*:Tc"
set-option -sa terminal-overrides ",xterm*:Tc,tmux-256color:Tc"

# Add ctrl+a as prefix
set-option -g prefix C-a
# Unbind default prefix (ctrl+b)
unbind C-b

bind C-a send-prefix

# Start index at 1
set-option -g base-index 1
set-option -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g allow-passthrough on

# Mouse
set-option -g mouse on

# Split window
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -c "#{pane_current_path}"

# Open in current working directory
bind c new-window -c "#{pane_current_path}"


## List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# tokyo night theme plugin
set -g @plugin 'fabioluciano/tmux-tokyo-night'

### tokyo night configuration
### Enable transparency
set -g @theme_variation 'storm'
# set -g @theme_plugins 'datetime'
set -g @theme_disable_plugins 1
set -g @theme_transparent_status_bar 'true'
set -g @theme_left_separator ''
set -g @theme_right_separator ''
set -g @theme_transparent_left_separator_inverse ''
set -g @theme_transparent_right_separator_inverse ''

# tmux resurrect & tmux continuum
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '10'



# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
